var nombre = "Alekhine";
var edad = 29;
var esDesarrollador = true;
var mes;
var variableNull = null;
console.log("Mes inicial:", mes);
mes = "Marzo";
console.log("Mes actualizado:", mes);
console.log("Hola mundooou! " + nombre);
console.log("Hola mundooou! ".concat(nombre));
